populate triangle
svalinn/dagmc_stats pull request #82
Opened 2021-05-06 13:03 UTC by yqin43

## Description
populate_triangle and its test are added

2021-05-06 13:24 UTC, kkiesling requested changes

2021-05-06 13:24 UTC, kkiesling commented on dagmc_stats/DagmcStats.py
> +                self._tri_data = self._tri_data.append(tri_data_row, ignore_index=True)
append this to a list of dictionaries and fill the data frame all at once when all data is calculated. `tri_data.append(tri_data_row)`

2021-05-06 13:24 UTC, kkiesling commented on dagmc_stats/DagmcStats.py
> +        tris = self.get_tris(meshset)
can initialize a list here `tri_data`

2021-05-06 13:24 UTC, kkiesling commented on dagmc_stats/DagmcStats.py
> +        return
return the list of dictionaries to populate the data frame in the init

2021-05-06 13:24 UTC, kkiesling commented on dagmc_stats/DagmcStats.py
> +            self.__populate_triangle_data(meshset)
move the creation of the data frame after this line so it can be populated all at once and save time

2021-05-06 13:26 UTC, kkiesling commented on dagmc_stats/DagmcStats.py
> +                self._tri_data = self._tri_data.append(tri_data_row, ignore_index=True)
so you'll have single list filled with dictionaries where each dictionary is one row

2021-05-06 13:35 UTC, kkiesling requested changes

2021-05-06 13:35 UTC, kkiesling commented on dagmc_stats/DagmcStats.py
> +    def __init__(self, filename, populate=False, meshset=None):
let's not pass in a meshset- we don't load the file yet so it doesn't make sense to be able to pass this.

2021-05-06 13:49 UTC, kkiesling reviewed
We need to have a larger discussion on the code lay out/design and how we want users to be calling this code I think before we can truly move forward.

2021-05-26 22:41 UTC, gonuke commented
It might be helpful to have a very short python script that shows how these classes will be used so that we make sure we have the same understanding.

2021-06-01 13:12 UTC, kkiesling requested changes
we should do two separate test files for each of the two new files `test_dagmcfile.py` and `test_dagmcquery.py`. Then we test the init for each class and the methods that exist in each file. So the Dagmc Query class needs the init tested and the `get_tri` tests should go in that same test file.

2021-06-01 13:12 UTC, kkiesling commented on dagmc_stats/DagmcQuery.py
> +    def __init__(self, dagmc_file, meshset=None):
init needs a doc string to describe the inputs and the purpose of the class

2021-06-01 13:16 UTC, kkiesling commented
> It might be helpful to have a very short python script that shows how these classes will be used so that we make sure we have the same understanding.

a short script for us or users? If the former, there are notes in the shared document that show the workflow. If the latter, I think that should come in another PR that gives examples.

2021-06-01 14:09 UTC, gonuke commented
> > It might be helpful to have a very short python script that shows how these classes will be used so that we make sure we have the same understanding.
> 
> a short script for us or users? If the former, there are notes in the shared document that show the workflow. If the latter, I think that should come in another PR that gives examples.

I as thinking of a minimal implementation for us.

2021-06-08 13:11 UTC, kkiesling commented
> > > It might be helpful to have a very short python script that shows how these classes will be used so that we make sure we have the same understanding.
> > 
> > 
> > a short script for us or users? If the former, there are notes in the shared document that show the workflow. If the latter, I think that should come in another PR that gives examples.
> 
> I as thinking of a minimal implementation for us.

Let's make a gist with the script..

2021-06-08 13:18 UTC, kkiesling approved these changes
this looks good now! Merging.

2021-06-08 13:18 UTC, merged

2021-06-08 13:48 UTC, kkiesling commented
> > > > It might be helpful to have a very short python script that shows how these classes will be used so that we make sure we have the same understanding.
> > > 
> > > 
> > > a short script for us or users? If the former, there are notes in the shared document that show the workflow. If the latter, I think that should come in another PR that gives examples.
> > 
> > 
> > I as thinking of a minimal implementation for us.
> 
> Let's make a gist with the script..

NVM - it's not easy to collaborate on a gist it seems. We'll add this as a script in this repo.